### PR TITLE
Mini bag

### PR DESCRIPTION
**Pull request by adiraomj**
Implemented the masthead mini cart.

@Misplon how do we implement it in the mobile menu? Any ideas?

### CODE REVIEW

**Comment by Misplon** [comment]
Awesome :) Thanks @adiraomj. 

Does the mini-cart show contents when you test?

mini-cart

Can we also introduce a setting to disable in the WooCommerce section?

**Comment by adiraomj** [comment]
I'm seeing the issue too. I'll test it out tomorrow. North also has this same problem!

**Comment by Misplon** [comment]
Ok great, let's fix both if possible. Thanks :)

**Comment by Misplon** [comment]
@adiraomj With regards to the mobile menu, can we do it like North? Do we need styles from Ric?

**Comment by adiraomj** [comment]
We can do it like north. :)

**Comment by Misplon** [comment]
Awesome :) Thanks

**Comment by adiraomj** [comment]
Fixed problem with dropdown items.
I had added a setting to display cart.
Made styling changes.
Cart items count updates without page load.
Added cart link to mobile menu.

**Pull request merged**
