### PR TITLE
Updated settings custom CSS

### PR DESCRIPTION
**Pull request by adiraomj**
Fixed bug #107

### CODE REVIEW

**Comment by Misplon** [comment]
Thanks @adiraomj we just need to make sure the button text stays white on hover.
hover

**Comment by adiraomj** [comment]
Done

**Comment by Misplon** [comment]
Just a quick fix here and I'll merge, thanks :)

**Comment by adiraomj** [comment]
Fixed merge conflict

Also moved WC custom CSS to a new function and outputs only when WC is active. Similar to https://github.com/siteorigin/siteorigin-north/pull/268

**Pull request merged**
