### PR TITLE
Wc variations styled

### PR DESCRIPTION
**Pull request by adiraomj**
Fixed bug #78 

Styled the select box.
Fixed the variations field in the quick view modal.
Updated the quick view styling.
Styled variable product in mini cart dropdown.

### CODE REVIEW

**Comment by Misplon** [comment]
Thanks @adiraomj. At the moment I'm getting:

```
Uncaught TypeError: $(...).find(...).wc_variation_form is not a function
    at Object.success (woocommerce.js?ver=dev:133)
    at i (jquery.js?ver=1.12.4:2)
    at Object.fireWith [as resolveWith] (jquery.js?ver=1.12.4:2)
    at y (jquery.js?ver=1.12.4:4)
    at XMLHttpRequest.c (jquery.js?ver=1.12.4:4)
```

Are you seeing anything like that? The clear link isn't working and no drop-down arrow is present. 

Thanks

**Comment by Misplon** [comment]
Thanks @adiraomj. Please, can you check, in the Quick View I'm not seeing the arrow on the right of the drop-down.

On the single product page, I do see the arrow (chevron) on the right of the drop-down.

Neither drop-down opens on hover but the drop-down on archive does open on hover, should we make that the same?

**Comment by Misplon** [comment]
Sorry this is dragging on. I think what Alex was going for on this one was the drop-downs looking the same.

drop-down

What you reckon? Should we just make the quick view drop-down fire on hover and style it like the archive sort?

**Comment by adiraomj** [comment]
Sorry for not replying. Had not seen this. I'll get on it now

**Comment by AlexGStapleton** [comment]
@Misplon That's correct. It seems odd to have a couple of "fancy" drop downs and then the standard drop downs for everything else.

**Comment by Misplon** [comment]
Thanks @adiraomj, think we're close.

single

quick-view

Also, at the moment, the drop-down background isn't styled like the sort order drop-down background. let me know if any of the above isn't clear. Thanks again :)

**Pull request merged**
