### PR TITLE
WooCommerce sidebar

### PR DESCRIPTION
**Pull request by adiraomj**
Altered layout of WooCommerce pages - sidebar is on the left now.
Styled all the default WooCommerce widgets.

@Misplon let me know if any changes are needed. Thanks :)

### CODE REVIEW

**Comment by Misplon** [comment]
Awesome, thanks :)

**Comment by Misplon** [comment]
Thanks @adiraomj. Hopefully, this isn't a caching issue. If no widgets are added to the shop sidebar, the archive and single pages aren't taking up the available container width. Is that happening for you?

**Comment by Misplon** [comment]
Thanks :)

Is the WooCommerce container filling the site container when no widgets are added to the Shop sidebar? At the moment, this is what I'm seeing locally.

shop

single

**Comment by adiraomj** [comment]
@Misplon please have a look now. Thanks

**Comment by Misplon** [comment]
Sorry about this. Quick fix when you can.

**Comment by adiraomj** [comment]
Done.. ;)

**Comment by Misplon** [comment]
@adiraomj Thanks :) Is this change working for you in live testing? It doesn't appear to be for me. The class is only true when both the regular sidebar and the shop sidebar are empty.

```
	// Check if the sidebar has widgets.
	$wc_shop_sidebar = function_exists( 'is_woocommerce' ) && is_woocommerce() && is_active_sidebar( 'shop-sidebar' );
	if ( ! is_active_sidebar( 'main-sidebar' ) && ! $wc_shop_sidebar ) {
		$classes[] = 'no-active-sidebar';
	}
```

**Comment by adiraomj** [comment]
@Misplon I added a new class if WC sidebar is not active. The logic to get it working with a single class was too twisted.

**Comment by Misplon** [comment]
Nice :) That's better. We still have a float that's winning:

```
.woocommerce-page .container #content {
    float: right;
    margin: 0 0 0 25.61404%;
}
```

That `float: right` is causing the width to remain at `900px`, once it's removed the width will use the full 1140. So just a little more adjustment needed. Thanks bro.

**Comment by adiraomj** [comment]
Please check it now. Thanks

**Comment by adiraomj** [comment]
I removed the sidebar from Woo single as we discussed on slack.

**Pull request merged**
