### PR TITLE
Correct invalid CSS

### PR DESCRIPTION
**Pull request by AlexGStapleton**
It's possible this change may result in a noticeable difference in spacing so please run some tests to identify if any undesired changes are noticeable.

### CODE REVIEW

**Comment by Misplon** [comment]
Thanks. 

Using default values, this will break the Menu inline with logo layout. The broken declaration was saving this layout. By correcting we'll be applying a height of 30px to that header layout by default.

**Comment by AlexGStapleton** [comment]
Ah. Feels like the way to go then would be to remove this line altogether then as it's not doing anything.

**Comment by Misplon** [comment]
The original idea with this line was most likely to make the header padding adjustable for layout 4. We should perhaps try make that happen.

**Comment by Misplon** [comment]
I see now. Yes, this rule can be removed. Thanks.

**Pull request merged**
