### PR TITLE
Added masthead bottom margin on home page

### PR DESCRIPTION
**Pull request by adiraomj**
Fixed bug #128.

### CODE REVIEW

**Comment by Misplon** [comment]
Thanks @adiraomj. I just noticed we're missing the bottom border:

post-details-header-03

Ric, did one layout when the slider isn't present, that doesn't have a border but Post-Details-Header-03 does.

**Comment by Misplon** [comment]
The bottom header border is missing in all layouts. Thanks man.

**Comment by adiraomj** [comment]
@Misplon I made the changes. Please test. :)

**Comment by Misplon** [comment]
Legend! Thanks dude, will test ASAP in the morning, GMT+2. Cheers.

**Pull request merged**
