### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by adiraomj**
Implemented enhancement #41 
Fixed bug #68 
Styled WC reviews.

Please check. Thanks.

### CODE REVIEW

**Comment by Misplon** [comment]
@adiraomj Thanks :) Looking awesome. Think we can make the search loading icon spin?

**Comment by adiraomj** [comment]
Done

**Comment by Misplon** [comment]
Looking awesome :) Just that one translation domain for reviews and we're good to go.

**Comment by adiraomj** [comment]
Done

**Pull request merged**
