### PR TITLE
Placed sticky sentinel before the top bar

### PR DESCRIPTION
**Pull request by adiraomj**
Implemented enhancement #145 

@Misplon & @AlexGStapleton  please test this out. Let me know how it works. Thanks

### CODE REVIEW

**Comment by Misplon** [comment]
@adiraomj I'm not seeing a difference. Do you when testing?

**Comment by Misplon** [comment]
@adiraomj @AlexGStapleton Sorry guys, too many tabs open, merged the wrong PR. Let's still work this though.

**Comment by adiraomj** [comment]
@Misplon Earlier the the entire menu bar had to be outside the screen for the menu to sticky.
With the this change the menu sticks as soon as the top of the menu bar goes beyond the screen.
Please let me know if this was unclear :)

**Comment by AlexGStapleton** [comment]
That's correct. It makes more sense to make it sticky it as soon as the menu is touched to allow for a smoother transition rather than doing it after it reaches the bottom which results in a noticeable jump in the menu.

**Comment by Misplon** [comment]
@AlexGStapleton Cool. Have you tested this PR? Happy?

**Pull request merged**
