### PR TITLE
Merge Lazy Load Logo Exclusion functions into single function

### LINKED ISSUE #259: Litespeed Cache Lazy Loading: Site Identity logo is being lazy loaded
Prevent Site Identity logo from being Lazy Loaded by Litespeed Cache.

### PR DESCRIPTION
**Pull request by AlexGStapleton**
Indirectly resolves #259

### CODE REVIEW

**Comment by Misplon** [comment]
Are we preventing the Jetpack Lazy Load function from targeting the logo? If not, let's add that, we can then mirror this function in Corp and North.

**Comment by Misplon** [comment]
With Smush, we're losing the default class and are seeing a space before the class.

SiteOrigin_–_Just_another_WordPress_site

**Comment by Misplon** [comment]
Litespeed lazy loading doesn't seem to be stopped if Smush is activated, is that intended?

**Comment by AlexGStapleton** [comment]
How does that look?

**Comment by Misplon** [comment]
_Litespeed lazy loading doesn't seem to be stopped if Smush is activated._

This still seems to be the case for me, have you tested?

**Comment by Misplon** [comment]
All working except for Jetpack.

**Comment by AlexGStapleton** [comment]
Ah crap, had another one of the plugins active so it appeared to have worked when I originally tested. :/

**Pull request merged**
