### PR TITLE
Sidebar placement

### PR DESCRIPTION
**Pull request by adiraomj**
Implemented enhancement #89 

Added settings to change position of main and shop sidebars.
Added necessary CSS.

@Misplon I also adjusted the Ordering dropdown CSS as we had discussed on slack. Please test. Thanks.

### CODE REVIEW

**Comment by Misplon** [comment]
Thanks @adiraomj. Please, could you check for us:

1. Responsive behaviour when main sidebar is set to left position. 

2. When shop sidebar is set to right position and no widgets are in shop sidebar the container is not full-width.

**Comment by adiraomj** [comment]
1. I had added necessary CSS for responsive behaviour. I'm not seeing any issue. What do you see? Is the sidebar not going below the content on smaller screens?
2. Fixed issue.

**Comment by Misplon** [comment]
Here is what I'm seeing on desktop:

**Comment by adiraomj** [comment]
This is what I am seeing

sidebar-left-responsive

Please check if this is conflicting with any other setting. Thanks.

**Comment by Misplon** [comment]
Thanks @adiraomj.

@AlexGStapleton Please, can you pull this PR and see if you can replicate my issue.

**Comment by AlexGStapleton** [comment]
Okay so I've tried it and I can't seem to replicate it.

Just to clarify:

- your layout sidebar is set to left and your shop sidebar is set to right.
- The shop sidebar is empty
- You're viewing a non-WooCommerce page, right? (in your image you're viewing what appears to be a blog post)

**Pull request merged**
