### PR TITLE
Updated WC functions to version 3.3.0

### PR DESCRIPTION
**Pull request by adiraomj**
@Misplon merge after WC is updated to 3.3.0

### CODE REVIEW

**Comment by AlexGStapleton** [comment]
Does this fix the product display changes to the archive? These settings are at **WP Admin > Appearance > Customize, WooCommerce > Product Catalogue**

**Comment by Misplon** [comment]
What are those changes? Haven’t looked yet.

I recommend 3.3.0 users roll back to 3.2.6 until the stable tag is
increased to 3.3.0. At that point we can push this update.

If users delete WC and reinstall they’ll now get 3.2.6

**Comment by AlexGStapleton** [comment]
They moved all of the product design options to the customizer and that seems to have broken the product catalog (for example) setting so now the product categories and products at the same time and this can't be disabled.

Good point.

**Comment by Misplon** [comment]
For sure. We can release an update to deal with this when 3.3.0 is released.

**Pull request merged**
