### PR TITLE
Ensure menu contents are vertically aligned

### PR DESCRIPTION
**Pull request by Misplon**
This PR ensures that the contents of the menu bar are always vertically aligned. It's a change in method and a bit of a refactor. This next release won't be backward compatible due to changes in the header PHP files so I guess we'll need to bump the version number to 1.5.

### CODE REVIEW

**Comment by AlexGStapleton** [comment]
The menu items are really small for me after enabling this branch. Are the menu items correctly sized for you?

Before:


After:

**Comment by Misplon** [comment]
They were always 12px: https://wordpress.org/themes/siteorigin-unwind/. I can bump up to 13px if you'd like?

**Comment by Misplon** [comment]
Ahh the hover area, yeah, that's an issue I didn't think about. Let me come back to you.

**Comment by Misplon** [comment]
I've pushed a solution, let me know your thoughts.

**Comment by Misplon** [comment]
Ok cool. Check out the four layouts and also Max Mega Menu and let me know. Thanks.

**Comment by AlexGStapleton** [comment]
Not seeing any issues with any of the other header layouts on desktop, or mobile. Not seeing any issues with Max Mega Menu with any of the Header Layouts on desktop, or mobile either.

**Comment by Misplon** [comment]
Super, thanks.

**Pull request merged**
