### PR TITLE
Video Format: Add Support For SO Video Player Widget

### PR DESCRIPTION
**Pull request by AlexGStapleton**
Resolve https://github.com/siteorigin/siteorigin-unwind/issues/312

Please test this using:

- The Classic Editor.
- The Block Editor.
- Self Hosted video
- External video

### CODE REVIEW

**Comment by Misplon** [comment]
Seems we're outputting the video twice from a Classic Editor post.

**Comment by Misplon** [comment]
*Self Hosted Videos*

Self-hosted videos don't replace the featured image using `develop`, perhaps we can resolve that in this PR.

With this branch in use, the self-hosted shortcode seems to be printing using the Classic Editor.

self-hosted-classic

Using Page Builder, the self-hosted video is on top but the featured image isn't removed.

self-hosted-classic

**Comment by Misplon** [comment]
**Block Editor:**

SiteOrigin Widget Block - Video Player Widget - External Video: Not working

Thanks, mate.

**Comment by AlexGStapleton** [comment]
@Misplon How does that look? I'm no longer able to replicate any of the reported issues. If you're able to, please let me know your specific setting/video combination - there are quite a few so it is possible I missed something.

**Comment by Misplon** [comment]
Thanks, mate. We've gone a bit deeper here than I would have wanted but what can we do. I'm seeing the following using the Block Editor:

```
Fatal error: Uncaught TypeError: Cannot access offset of type string on string in /Users/amisplon/Sites/siteorigin/wp-content/themes/siteorigin-unwind/inc/template-tags.php:759 Stack trace: #0 /Users/amisplon/Sites/siteorigin/wp-content/themes/siteorigin-unwind/inc/template-tags.php(837): siteorigin_unwind_panels_get_panels_data() #1 /Users/amisplon/Sites/siteorigin/wp-content/themes/siteorigin-unwind/template-parts/content-video.php(28): siteorigin_unwind_get_video(true) #2 /Users/amisplon/Sites/siteorigin/wp-includes/template.php(772): require('/Users/amisplon...') #3 /Users/amisplon/Sites/siteorigin/wp-includes/template.php(716): load_template('/Users/amisplon...', false, Array) #4 /Users/amisplon/Sites/siteorigin/wp-includes/general-template.php(204): locate_template(Array, true, false, Array) #5 /Users/amisplon/Sites/siteorigin/wp-content/themes/siteorigin-unwind/single.php(23): get_template_part('template-parts/...', 'video') #6 /Users/amisplon/Sites/siteorigin/wp-includes/template-loader.php(106): include('/Users/amisplon...') #7 /Users/amisplon/Sites/siteorigin/wp-blog-header.php(19): require_once('/Users/amisplon...') #8 /Users/amisplon/Sites/siteorigin/index.php(17): require('/Users/amisplon...') #9 {main} thrown in /Users/amisplon/Sites/siteorigin/wp-content/themes/siteorigin-unwind/inc/template-tags.php on line 759
```

**Comment by Misplon** [comment]
Yeah, we've gone down the rabbit hole here.

In `develop` if you insert a locally hosted video in the Classic Editor it won't display on the archive page if you're using the video post type. However, it will display on the single post page. When switching to this branch, the video is being removed from the single post page.

**Comment by Misplon** [comment]
I can no longer replicate the issue of a self-hosted video being stripped from the single post page so no worries there.

**Comment by Misplon** [comment]
I think what we could do is resolve the fatal error and then merge this PR. The following can be dealt with in separate PR's should we choose to do so:

* Video post format support for a locally hosted video inserted into the Classic Editor.
* SiteOrigin Video Player Widget support in the SiteOrigin Widget Block.

We could perhaps exclude the other possibilities and document which options are supported for the Video Post Format.

**Comment by AlexGStapleton** [comment]
I wasn't able to replicate the fatal error but I've come up with a method to prevent it. Let me know if it's still occuring.

The same functionality is present in North and Corp so we could duplicate any changes made in this PR to those themes. Hm. It may be better to add it as a theme settings extra to cut down on duplicate code (this is similar to what we did with the lazy loading functionality).

> Video post format support for a locally hosted video inserted into the Classic Editor.

I think adding support for locally hosted videos inserted locally makes a lot of sense.

> SiteOrigin Video Player Widget support in the SiteOrigin Widget Block.

This also makes a lot of sense, but it's not as large as a priority imo.

**Comment by Misplon** [comment]
In the Classic Editor can you spot why a self-hosted video isn't getting the `entry-video` wrapper?

**Comment by Misplon** [comment]
I'm not proposing we add further support unless requested but ideally we should avoid negative support. In the Block Editor, the YouTube block has its video removed but not displayed.

**Comment by Misplon** [comment]
The issue seems to have been resolved but I'm seeing two videos now.

- Block Editor.
- YouTube Video.

**Comment by Misplon** [comment]
In the Block Editor using a Video Block (self-hosted), it looks like the featured image is present and the video isn't playing:

Hello_world__–_SiteOrigin

**Comment by AlexGStapleton** [comment]
> In the Classic Editor can you spot why a self-hosted video isn't getting the entry-video wrapper?

I can't seem to replicate this - the video is getting the `entry-video` wrapper for me. 

> The issue seems to have been resolved but I'm seeing two videos now.

Was this both issues, or YouTube block being removed?

> I'm seeing two videos now.

I can't replicate this either. I've uploaded a build of this PR to the demo site and you can see this here: https://demo.siteorigin.com/unwind/313-be-external-2/

For reference, [here's a copy of the build](https://drive.google.com/uc?id=1_vuUewJUAgSe_hViN4uDxXOIniB2Rs7m).

> In the Block Editor using a Video Block (self-hosted), it looks like the featured image is present and the video isn't playing:

Resolved. The video block isn't currently supported but it previously wasn't being broken so I've fixed this.

**Comment by Misplon** [comment]
Thanks, mate.

**In the Classic Editor can you spot why a self-hosted video isn't getting the entry-video wrapper?**

Please, see https://demo.siteorigin.com/unwind/
Private: #313 BE External

I'll check on the other issues once you've confirmed this one.

**Comment by AlexGStapleton** [comment]
Thanks. That video isn't supported by this functionality which is why the container isn't picked up. This is in line with previous versions and to verify this I've restored the release version of Unwind.

Only videos added using the SiteOrigin Video Player widget or are externally hosted videos (hosted using an oEmbed friendly service like YouTube) get picked up. 

https://demo.siteorigin.com/unwind/313-be-external/

**Comment by Misplon** [comment]
Super, thanks, I think we're there.

**Review by Misplon — APPROVED** [review]

**Pull request merged**
